const VALIDATE_DATA  = 'VALIDATE_DATA'
const GENRES_DATA    = 'GENRES_DATA'
const COUNTRIES_DATA = 'COUNTRIES_DATA'
const LENGUAGES_DATA = 'LENGUAGES_DATA'
const JOBS_DATA      = 'JOBS_DATA'
const VALIDATE_DATA_ASYNC  = 'VALIDATE_DATA_ASYNC'
const GENRES_DATA_ASYNC    = 'GENRES_DATA_ASYNC'
const COUNTRIES_DATA_ASYNC = 'COUNTRIES_DATA_ASYNC'
const LENGUAGES_DATA_ASYNC = 'LENGUAGES_DATA_ASYNC'
const JOBS_DATA_ASYNC      = 'JOBS_DATA_ASYNC'

export {
	COUNTRIES_DATA,
	GENRES_DATA,
	LENGUAGES_DATA,
	JOBS_DATA,
	VALIDATE_DATA,
	COUNTRIES_DATA_ASYNC,
	GENRES_DATA_ASYNC,
	LENGUAGES_DATA_ASYNC,
	JOBS_DATA_ASYNC,
	VALIDATE_DATA_ASYNC,
}