const ADD_MOVIES           = 'ADD_MOVIES'
const FIND_MOVIE           = 'FIND_MOVIE'
const FIND_MOVIE_SLIDER    = 'FIND_MOVIE_SLIDER'
const FIND_MOVIE_LIST      = 'FIND_MOVIE_LIST'
const FIND_LIST_PROVIDERS  = 'FIND_LIST_PROVIDERS'
const FIND_LIST_SIMILAR    = 'FIND_LIST_SIMILAR'
const FIND_LIST_RECOMENDED = 'FIND_LIST_RECOMENDED'
const FIND_LIST_CREDIT     = 'FIND_LIST_CREDIT'
const FIND_LIST_REVIEW     = 'FIND_LIST_REVIEW'
const FIND_LIST_VIDEO      = 'FIND_LIST_VIDEO'
const REMOVE_MOVIES        = 'REMOVE_MOVIES'
const SEARCH_MOVIE         = 'SEARCH_MOVIE'
const SET_FILTER           = 'SET_FILTER'
const ADD_MOVIES_ASYNC           = 'ADD_MOVIES_ASYNC'
const FIND_MOVIE_ASYNC           = 'FIND_MOVIE_ASYNC'
const FIND_MOVIE_SLIDER_ASYNC    = 'FIND_MOVIE_SLIDER_ASYNC'
const FIND_MOVIE_LIST_ASYNC      = 'FIND_MOVIE_LIST_ASYNC'
const FIND_LIST_PROVIDERS_ASYNC  = 'FIND_LIST_PROVIDERS_ASYNC'
const FIND_LIST_SIMILAR_ASYNC    = 'FIND_LIST_SIMILAR_ASYNC'
const FIND_LIST_RECOMENDED_ASYNC = 'FIND_LIST_RECOMENDED_ASYNC'
const FIND_LIST_CREDIT_ASYNC     = 'FIND_LIST_CREDIT_ASYNC'
const FIND_LIST_REVIEW_ASYNC     = 'FIND_LIST_REVIEW_ASYNC'
const FIND_LIST_VIDEO_ASYNC      = 'FIND_LIST_VIDEO_ASYNC'
const SEARCH_MOVIES_ASYNC        = 'SEARCH_MOVIES_ASYNC'
const SET_FILTER_ASYNC           = 'SET_FILTER_ASYNC'

export {
	ADD_MOVIES,
	FIND_MOVIE_SLIDER,
	FIND_MOVIE,
	FIND_MOVIE_LIST,
	FIND_LIST_PROVIDERS,
	FIND_LIST_SIMILAR,
	FIND_LIST_RECOMENDED,
	FIND_LIST_CREDIT,
	FIND_LIST_REVIEW,
	FIND_LIST_VIDEO,
	REMOVE_MOVIES,
	SEARCH_MOVIE,
	SET_FILTER,
	ADD_MOVIES_ASYNC,
	FIND_MOVIE_ASYNC,
	FIND_MOVIE_SLIDER_ASYNC,
	FIND_MOVIE_LIST_ASYNC,
	FIND_LIST_PROVIDERS_ASYNC,
	FIND_LIST_SIMILAR_ASYNC,
	FIND_LIST_RECOMENDED_ASYNC,
	FIND_LIST_CREDIT_ASYNC,
	FIND_LIST_REVIEW_ASYNC,
	FIND_LIST_VIDEO_ASYNC,
	SEARCH_MOVIES_ASYNC,
	SET_FILTER_ASYNC,
}